name: reusable
on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string
        default: dist
    outputs:
      result:
        value: ${{jobs.deploy.outputs.outcome}}
jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      outcome: ${{steps.set-result.outputs.set-result}}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{inputs.artifact-name}}
      - name: Deployments
        run: echo "Deploying...""
      - name: set-result
        run: echo "::set-output name=step-result::success"