name: reusable
on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string
        default: dist
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{inputs.artifact-name}}
      - name: Deployments
        run: echo "Deploying...""